name: Publish Homebrew Tap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zshrc
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Create Tap
        run: |
          echo "${{secrets.GITHUBUSER.GITHUBUSER}}"
    # brew tap $GITHUBUSER/$GITHUBREPO

     # - name: Install Formula
      #  run: |
       #   brew install {{your_formula_name}}
